configurator/urls.py
from django.urls import path
from . import views

app_name = 'configurator'

urlpatterns = [
    path('configurator/', views.configurator, name='configurator'),
]

gym_helper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('', include('main.urls')),
    path('', include('configurator.urls'))
]

main/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
]

configurator/models.py
from django.db import models
from users.models import User


class Training(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    train_place = models.CharField(max_length = 100)
    train_type = models.CharField(max_length = 100)
    train_program = models.CharField(max_length = 100, null=True, blank=True)
    day_week = models.JSONField(null=True, blank=True)  
    muscle_groups = models.JSONField(null=True, blank=True) 
    difficulty = models.CharField(max_length = 100)  
    train_plan = models.JSONField(null=True, blank=True)


    def __str__(self):
        return self.user.username

main/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_premium = models.BooleanField(default=False)

    class Meta:
        db_table = 'user'
    
    def __str__(self):
        return self.username

configurator/views.py
from django.shortcuts import render, redirect
from .models import Training
from .ai_train import generate_workout_plan


def configurator(request):
    if request.method == 'POST':
        config = Training()
        config.user = request.user
        config.train_place = request.POST.get('train-place')
        config.train_type = request.POST.get('train-type')
        config.train_program = request.POST.get('train-program')
        config.day_week = request.POST.getlist('day-week')
        config.muscle_groups = request.POST.getlist('muscle-groups')
        config.difficulty = request.POST.get('difficulty')

        config.train_plan = generate_workout_plan(train_place=config.train_place,
                                                train_type=config.train_type,
                                                train_program=config.train_program,
                                                day_week=config.day_week,
                                                muscle_groups=config.muscle_groups,
                                                difficulty=config.difficulty)

        config.save()

        return redirect('users:profile')

    return render(request, 'configurator/configurator.html')

def it_works(request):
    return render(request, 'configurator/itworks.html')

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'main/index.html')

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from users.models import User
from django.contrib import messages


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect(reverse('users:profile'))
        else:
            return render(request, 'users/users.html')
    return render(request, 'users/users.html')

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        
        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()
        
        auth_login(request, user)
        return redirect('users:profile')
    
    return redirect('users:login')


def profile(request):
    return render(request, 'users/profile.html')


def logout(request):
    auth_logout(request)
    return redirect('users:login')

configurator/templates/configurator/itworks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> ИТ ВОРКС </h1>
</body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная</title>
</head>
<body>
    <a href="user/login" class="login"> Войти </a>
</body>
</html>

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    <p>Привет, {{ user.username }}!</p>
    <a href="../../configurator/" class="configurator">Конфигуратор</a>
    <form action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Выйти</button>
    </form>
</body>
</html>

users/templates/users/users.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Форма авторизации и регистрации</title>
  <link rel="stylesheet" href="{% static '/deps/css/style.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous">

<div class="container" id="container">
        <div class="form-container sign-up-container">
            <form action="{% url 'users:register' %}" method="POST">
                <h1>Регистрация</h1>
                <span>или используйте свой E-mail для регистрации</span>
                <input type="text" name="username" placeholder="Name" required />
                <input type="email" name="email" placeholder="Email" required />
                <input type="password" name="password" placeholder="Password" required />
    
                {% csrf_token %}
    
                <button type="submit">Зарегистрироваться</button>
            </form>
        </div>
        <div class="form-container sign-in-container">
            <form action="{% url 'users:login' %}" method="POST">
                <h1>Авторизация</h1>
                <span>или используйте свой аккаунт</span>
                <input type="text" name="username" placeholder="Name" />
                <input type="password" name="password" placeholder="Password" />
                <a href="#">Забыли пароль?</a>
            
                {% csrf_token %}
            
                <button>Вход</button>
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Добро пожаловать!</h1>
                    <p>Чтобы оставаться на связи с нами, пожалуйста, войдите в систему с вашей личной информацией</p>
                    <button class="ghost" id="signIn">Авторизация</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>Привет, Друг!</h1>
                    <p>Введите свои личные данные и начните путешествие вместе с нами</p>
                    <button class="ghost" id="signUp">Регистрация</button>
                </div>
            </div>
        </div>
    </div>
<!-- partial -->
  <script  src="{% static "/deps/js/script.js" %}"></script>

</body>
</html>